title: "99linesofcode"
hide_post_share: true
hide_post_date: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# jekyll-paginate settings
paginate: 5

# jekyll-feed settings
author: "Jordy Schreuders"
