menu:
- {name: 'Archive', url: 'writing.html'}

social:
- {icon: 'github', link: 'https://www.github.com/99linesofcode'}
- {icon: 'twitter', link: 'https://twitter.com/jordyschreuders'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/99linesofcode'}
- {icon: 'envelope', link: 'mailto:99linesofcode+blog@gmail.com'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Let others know you enjoyed this post!'
related_posts: 'You may also enjoy reading:'
post_date_prefix: 'Written on'
